# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 445cd139500e13bce41c9f2a7281ac908fa864a3fc0f164ac3a81a6490947b5e9a1677803eab506b1c8ceadf3c8971c26b44bf608157fd4eb6e64ef50c5fc380

test:
  secret_key_base: b2a515bf23575ca33cea5f7dbd32f049dd8a02ac55940cd0cc41d2a1756848de48f42cf925b67a1e52c319ca99a0c6a867972fe4dd27f6ab298fc45f98355c56

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
