#!/bin/bash

set -uo pipefail

appdir=$(cd $(dirname "$0")/.. && pwd)
[ -f /etc/app-env ] || exec "$appdir/script/app-env" $0 $@

for i in {1..60}; do
  curl -sf db:3306 >/dev/null && exit
  sleep 1
done

echo "Unable to reach database!"
exit 1
